@startuml installations

component client{

}

component VPS {
    port p
    database postgresql{
        port p7
    }
    component django{
        portin p5
        portout p6
    }
    component gunicorn{
        portin p3
        portout p4
    }
    component nginx{
        portin p1
        portout p2
    }
}

client --> p
p <-> p1
p2 <--> p3
p4 <--> p5
p6 <--> p7



@enduml