@startuml

hide circle

entity "user" as User{
    
}

entity "arrow" as Arrow {

}

entity "quiver" as Quiver{

}

entity "bow" as Bow{

}

entity "practice session" as PracticeSession{

}

entity "stats session" as StatsSession{

}

User ||--o{ Arrow
User ||--o{ Bow
User ||--o{ PracticeSession
User ||--o{ StatsSession
User ||--o{ Quiver

Arrow }|--|{Quiver
Arrow }|--{ PracticeSession
Arrow }|--{ StatsSession
@enduml