name: CI base
on: [push]
jobs:
  setup all OS dependencies:
    run-on: alpine:latest
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: setup sqlite
      uses: actions/setup-sqlite@v1
      with:
        sqlite-version: 3.40.0
        sqlite-year: 2022
    - name: setup nodejs and npm
      uses: actions/setup-node@v3
  with:
    node-version: 16
    - name: setup poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: 1.1.13
    - name: View poetry --help
        run: poetry --help